baseURL: nikolamilovic.com
languageCode: en-us
title: Nikola Milovic
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: true

pagination:
  pagerSize: 5
minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS

params:
  social: true #https://github.com/adityatelange/hugo-PaperMod/issues/1573

  plausible:
    enable: true
    gitstar: false
    domain: blog.nikolamilovic.com
  homeInfoParams:
    Title: How did you end up here?
    Content: |
      My name is Nikola, and I am a Software Developer, currently taking a break from corporate gigs, working on 
      [Seolitic](https://seolitic.com/)(automatic seo for ecommerce), [Kipap](https://kipap.ai/)(todo-ish app)

      Follow me on my socials i swear I'll post something someday

  socialIcons:
    - name: rss
      url: "https://nikolamilovic.com/index.xml"
    - name: "x"
      url: "https://x.com/nikolamilovic5"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nikola-milovic/"
    - name: "github"
      url: "https://github.com/Nikola-Milovic"

  keywords:
    - Blog
  author: Nikola Milovic
  defaultTheme: auto
  DateFormat: Jan 2, 2006

  # ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  ShowFullTextInRSS: true

  UseHugoToc: true
  # disableSpecial1stPost: true
  # disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false

  ShowToc: true
  TocOpen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true

  cover:
    hiddenInList: true

  editPost:
    URL: https://github.com/Nikola-Milovic/blog/content
    Text: Suggest Changes
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: posts
      name: ~ posts
      url: /posts/
      weight: 10

pygmentsUseClasses: true
markup:
  highlight:
    style: nord
  goldmark:
    parser:
      attribute:
        block: true # allow parsing of blocks

module:
  imports:
    - path: "github.com/divinerites/plausible-hugo"
